name: Oma-opiskelijavalinnan build workflow
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "**.md"
env:
  HUSKY: 0
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint-and-test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version-file: ".java-version"
          distribution: "corretto"
          cache: "maven"
      - name: Lint Scala project
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn spotless:check
      - name: Test Scala project
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn test
  lint-and-test-frontend:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./oma-opiskelijavalinta-ui
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-env
        with:
          project_path: oma-opiskelijavalinta-ui
      - name: Check types
        run: pnpm run typecheck
      - name: Run linter
        run: pnpm run lint
      - name: Run unit tests
        run: pnpm run test
  build-backend:
    runs-on: ubuntu-latest
    needs:
      - lint-and-test-backend
      - lint-and-test-frontend
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version-file: ".java-version"
          distribution: "corretto"
          cache: "maven"
      - uses: ./.github/actions/setup-node-env
        with:
          project_path: oma-opiskelijavalinta-ui
      - name: Build and copy frontend to backend static-dir
        run: |
          cd oma-opiskelijavalinta-ui
          pnpm run build-and-copy

      - name: Build Scala project
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn clean package

      - uses: actions/cache@v4
        id: restore-build
        with:
          path: |
            target
          key: ${{ github.sha }}
  test-playwright:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./oma-opiskelijavalinta-ui
    container:
      image: mcr.microsoft.com/playwright:v1.56.1-noble
      options: --user 1001
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-env
        with:
          project_path: oma-opiskelijavalinta-ui
      - name: Build app
        run: pnpm run build:test
      - name: Run Playwright tests
        run: pnpm run start-and-test-playwright-ci
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 10
          if-no-files-found: ignore
  deploy-container:
    needs:
      - build-backend
      - test-playwright
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        id: restore-build
        with:
          path: |
            target
          key: ${{ github.sha }}

      - name: Build and deploy Docker container
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          git clone https://github.com/Opetushallitus/ci-tools.git
          source ci-tools/common/setup-tools.sh

          export ARTIFACT_NAME="oma-opiskelijavalinta"
          mv target/oma-opiskelijavalinta-exec.jar $DOCKER_BUILD_DIR/artifact/${ARTIFACT_NAME}.jar
          cp -vr src/main/resources/oph-configuration $DOCKER_BUILD_DIR/config/
          export BASE_IMAGE="baseimage-fatjar-openjdk21:master"
          ./ci-tools/common/pull-image.sh
          ./ci-tools/github-build/build-fatjar.sh $ARTIFACT_NAME
          ./ci-tools/github-build/upload-image.sh $ARTIFACT_NAME
